# Generated by Django 5.0.6 on 2024-06-06 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanpham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_San_Pham', models.CharField(max_length=200, null=True)),
                ('gia', models.FloatField()),
                ('digital', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('nguoi_dung', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat_hang', models.DateTimeField(auto_now_add=True)),
                ('Hoan_thanh', models.BooleanField(default=False, null=True)),
                ('id_khach_Hang', models.CharField(max_length=200, null=True)),
                ('nguoi_mua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(blank=True, default=0, null=True)),
                ('ngay_mua', models.DateTimeField(auto_now_add=True)),
                ('dat_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order')),
                ('san_pham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ThongTinKhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_chi', models.CharField(max_length=200, null=True)),
                ('thanh_pho', models.CharField(max_length=200, null=True)),
                ('tinh_thanh', models.CharField(max_length=200, null=True)),
                ('so_dien_thoai', models.CharField(max_length=200, null=True)),
                ('ngay_mua', models.CharField(max_length=200, null=True)),
                ('dat_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order')),
                ('nguoi_mua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachhang')),
            ],
        ),
    ]
