# Generated by Django 5.0.6 on 2024-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
