# Generated by Django 5.0.6 on 2024-06-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='category',
            field=models.ManyToManyField(related_name='san_pham', to='app.category'),
        ),
    ]
